name: Domain Audit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # weekly audit tiap minggu

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run audit
        run: |
          python domain_audit.py --domain rupiahid-dompet.my.id --json-out audit-report.json || true
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json
